### ISSUE TITLE
Parsing Error for ADT Output with SSA Pass

### ISSUE THREAD

**Issue by zzrcxb** [BinaryAnalysisPlatform/bap-python#12]
Hi all,

I really enjoy using BAP, but I encountered some bugs today while using SSA pass. I attached the minimal reproducible source code and the compiled binary.
[phi.zip](https://github.com/BinaryAnalysisPlatform/bap-python/files/3587353/phi.zip)

Configurations:
- OS: Debian 9.9
- BAP: 1.6.0
- bap-python: 1.3.1

I invoked BAP with: `bap.run('a.out', args=['--pass=ssa'])` and got
```
Traceback (most recent call last):
  File "./run.py", line 14, in <module>
    proj = bap.run(args.filename, args=['--pass=ssa'])
  File "[truncated]/lib/python3.5/site-packages/bap/bap.py", line 124, in run
    return parser['load'](out)
  File "[truncated]/lib/python3.5/site-packages/bap/bir.py", line 369, in loads
    return noeval_parser.parser(s)
  File "[truncated]/lib/python3.5/site-packages/bap/noeval_parser.py", line 328, in parser
    result = _parser(input_str, logger=logger)
  File "[truncated]/lib/python3.5/site-packages/bap/noeval_parser.py", line 282, in _parser
    i = parse_func(in_c, in_s, i, objs, stk)
  File "[truncated]/lib/python3.5/site-packages/bap/noeval_parser.py", line 207, in _parse_end
    parent = objs[j] = getattr(bir, name)(*parent.get('children', ())) # pylint: disable=redefined-variable-type
  File "[truncated]/lib/python3.5/site-packages/bap/adt.py", line 509, in __init__
    self.elements = dict((x.arg[0],x.arg[1]) for x in args[0])
  File "[truncated]/lib/python3.5/site-packages/bap/adt.py", line 509, in <genexpr>
    self.elements = dict((x.arg[0],x.arg[1]) for x in args[0])
AttributeError: 'tuple' object has no attribute 'arg'
```

After examing the traceback and your source code, I believe it's either a bug in SSA pass that outputs malformed ADT string or a bug of the parser that fails to handle tuples.

Use `bap.noeval_parser.parser` to parse
```
Phi(Tid(0x00000237, "%00000237"), Attrs([]), Var("RBX.2",Imm(64)), Values([(Tid(0x00000049, "%00000049"),Var("RBX.1",Imm(64))),(Tid(0x0000005a, "%0000005a"),Var("RBX.3",Imm(64)))]))
```
can reproduce the bug. The string is a part of output from SSA pass that caused the problem (`Values([(Tid(0x00000049, "%00000049"),Var("RBX.1",Imm(64))),(Tid(0x0000005a, "%0000005a"),Var("RBX.3",Imm(64)))])` is the root cause, Values should contain a list of ADT objects rather than a list of tuples).

I already sent a pull request #11 that contains a quick workaround on the bap-python side.

**Comment by ivg** [comment]
Thanks for the detailed report and for the fix! It was indeed a bug on the printing side, but I think that it is better to fix it on the parser side and officially decide that this would be the syntax for the Phi nodes. Let's move the discussion to the PR, though :)
