### ISSUE TITLE
Missing small imports in adt.py

### ISSUE THREAD

**Issue by tylerni7** [BinaryAnalysisPlatform/bap-python#2]
`adt.py` seems to be missing an import for `bap.bir.Tid`, so an attempt at using `find` with a key of that type fails (such as the simple example on the main page)

**Comment by ivg** [comment]
Yeah, it was originally in the bir module, but later we lifted it into adt module. Will fix in the next release, thanks for the report!

**Comment by ivg** [comment]
Fixed with #6.
